# Generated by Django 6.0.1 on 2026-02-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
    ]
