# Generated by Django 6.0.1 on 2026-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_seat_is_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
