# Generated by Django 6.0.1 on 2026-02-18 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bus_image_bus_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
