# Generated by Django 6.0.1 on 2026-02-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_journey_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='journey_date',
        ),
    ]
