# Generated by Django 6.0.1 on 2026-02-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_booking_journey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
